POST http://localhost:8181/api/person
Content-Type: application/json
Accept: application/json

{
  "firstName" : "Eko",
  "middleName": "Kurniawan",
  "lastName": "Khannedy",
  "email": "eko@example.com",
  "phone": "082034234324",
  "hobbies": ["Coding", "Gaming"],
  "socialMedias": [
    {
      "name": "Facebook",
      "location": "facebook.com/ProgrammerZamanNow"
    }
  ]
}


###

POST http://localhost:8181/todos?todo=Belajar Java
Accept: application/json

###

GET http://localhost:8181/todos
Accept: application/json
